# Generated by Django 2.0.2 on 2018-02-23 21:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('webpage', models.URLField()),
                ('institution', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=70)),
                ('position', models.CharField(max_length=30)),
                ('grad_date', models.DateField()),
                ('brain_structure', models.CharField(max_length=30)),
                ('modalities', models.CharField(max_length=50)),
                ('methods', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=30)),
                ('keywords', models.CharField(max_length=250)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('reviewer_position', models.CharField(max_length=30)),
                ('seen_at_conf', models.BooleanField()),
                ('comment', models.CharField(max_length=500)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewlist.Profile')),
            ],
        ),
    ]
