# Generated by Django 2.0.2 on 2018-03-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewlist', '0002_auto_20180302_0912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommandation',
            new_name='Recommendation',
        ),
    ]
