# Generated by Django 2.0.2 on 2018-03-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewlist', '0003_auto_20180302_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('is_under_represented', models.BooleanField(default=False)),
            ],
        ),
    ]
