# Generated by Django 2.0.2 on 2018-03-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewlist', '0005_auto_20180302_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grad_date',
            field=models.DateField(blank=True),
        ),
    ]
