# Generated by Django 2.0.2 on 2018-03-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewlist', '0006_auto_20180303_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grad_date',
            field=models.DateField(null=True),
        ),
    ]
